### ISSUE TITLE
Redirects occur to wrong rating page

### ISSUE THREAD

**Issue by Cosworth32** [tr0ldmand/com_bloodbowl25#10]
browse to http://trc.dk/index.php/blood-bowl/rating-turneringen. Select "show only teams from coach xx" and submit. The redirect then points to the rating 2013 and not rating 2014. Judging from the amount of incorrectly created matches for this old tournament this happens frequently and is very confusing.

**Comment by Cosworth32** [comment]
tournament 29 is hard coded here:
views/tourneydetail/view.html.php

**Comment by Cosworth32** [comment]
I'll close this one for now.

**Comment by tr0ldmand** [comment]
Is probably a mix of several issues:
1. Models use a hardcoded value for the standard tourney id, instead of using getNewestTour static method ( BloodBowlTableTourney::getNewestTour()->tour_id )
2. Views/templates use a hardcoded value for standard tourney id, instead of asking the model for the current id
3. The form at views/tourneydetail/tmpl/default_rating.php line 58 is wrong in some way
